webtalk_init -webtalk_dir /home/czaras/Projekty/studia/IUP/fpga-projects-iup/frequency_divider/frequency_divider.sim/sim_1/behav/xsim/xsim.dir/divider_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 13 16:13:25 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "924508d9-a381-48fc-bd8b-5a05064caa60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "79bcee9e70904e8f9aaf48eecf8c7959" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4500U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1689.903 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114232_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3466850906 -regid "" -xml /home/czaras/Projekty/studia/IUP/fpga-projects-iup/frequency_divider/frequency_divider.sim/sim_1/behav/xsim/xsim.dir/divider_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/czaras/Projekty/studia/IUP/fpga-projects-iup/frequency_divider/frequency_divider.sim/sim_1/behav/xsim/xsim.dir/divider_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/czaras/Projekty/studia/IUP/fpga-projects-iup/frequency_divider/frequency_divider.sim/sim_1/behav/xsim/xsim.dir/divider_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
