webtalk_init -webtalk_dir /home/czaras/Projekty/studia/IUP/fpga-projects-iup/ps2_interface/ps2_interface.sim/sim_1/behav/xsim/xsim.dir/ps2_interface_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 31 12:45:42 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "924508d9-a381-48fc-bd8b-5a05064caa60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cef63fe6b5164cedafdebeab4317972c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "63" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4500U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3467.551 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "118396_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1663891397 -regid "" -xml /home/czaras/Projekty/studia/IUP/fpga-projects-iup/ps2_interface/ps2_interface.sim/sim_1/behav/xsim/xsim.dir/ps2_interface_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/czaras/Projekty/studia/IUP/fpga-projects-iup/ps2_interface/ps2_interface.sim/sim_1/behav/xsim/xsim.dir/ps2_interface_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/czaras/Projekty/studia/IUP/fpga-projects-iup/ps2_interface/ps2_interface.sim/sim_1/behav/xsim/xsim.dir/ps2_interface_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
